const HOME_DATA  = 
  {
    "intro":"The next step is to begin tracking your sleep patterns. Please take a few minutes to fill out a sleep diary each morning for the next 2 weeks. This lets us know your starting point. If you forget to record your answers one morning, you can go back and fill them in up to a day later.",
    "subhead1":"Sleep diary instructions:",
    "intro1":"The sleep diary is very brief. It should only take a few minutes to complete. If you don’t know the exact times, record your best guess.",
    "bullet1":"•	Record the time you got into bed.",
    "bullet2":"•	Record the time you began to try to fall asleep.",
    "bullet3":"•	Estimate the time when you fell asleep.",
    "bullet4":"•	Record how many times you woke up during the night.",
    "bullet5":"•	Record how long you were awake each time.",
    "bullet6":"•	Record the time you woke up and stayed awake.",
    "bullet7":"•	Record the time you got out of bed to start your day. This should be after your final awakening.",
    "bullet8":"•	Rate the overall quality of your sleep.",
    "bullet9":"•	Note any medications or other sleep aids taken before going to bed.",
    "description":"Please fill out a sleep diary each day. It is best to do this as soon as you get out of bed so that you don’t forget. You can also use the Medication log at any time to record any medications you are taking."
  };

  const LEVEL1_DATA = 
  {
    "splashBullet1": "You will see that new information is available to you within the Health enSuite app.",
    "splashBullet2": "Health enSuite Insomnia consists of a series of levels or content chapters. Each level has tasks you will need to complete before you can advance to the next level. These tasks include reading about new strategies for improving your sleep, watching videos, answering questions, completing daily sleep diaries, and tracking your medications. Each level is designed to take about one week to complete so that by the end of 6 weeks you will have completed the entire program.",
    "bullet1": "Health enSuite Insomnia is designed to support you in changing your habits and improving your sleep. The advice it contains should complement, but does not replace, the services you receive from your health care provider.",
    "bullet2": "The main goals for this first week are for you to continue tracking your sleep patterns using the sleep diaries, and learn about some of the common causes and consequences of insomnia.",
    "bullet3": "It may also be time to start reducing your use of sleeping pills. Follow the medication schedule recommended by your health care provider.",
    "subHead1": "To advance to the next level you will need to:",
    "bullet4": "- Complete at least 5 sleep diaries within a week",
    "bullet5": "- Complete the readings and activities for level 1 (Introduction to Health enSuite)",
    "bullet6": "Insomnia is more than just getting a poor night’s sleep. Everyone can have difficulty sleeping from time to time. For people with insomnia, difficulty sleeping becomes a regular and persistent problem. This could involve difficulty falling asleep, difficulty staying asleep, or both. Some people with insomnia wake up frequently throughout the night and have trouble getting back to sleep. Others wake up too early in the morning.",
    "bullet7": "Insomnia is not the result of a lack of opportunity to sleep. People with insomnia experience sleep disruptions even though they had a reasonable chance to sleep.",
    "subHead2": "Which of the following best describes your situation (check all that apply):",
    "bullet8": "Usually, insomnia is not caused by a chemical imbalance. Most of the time it is caused by habits, lifestyle, and problematic ways of thinking about sleep. Solutions that focus on these underlying causes of insomnia have the best chance of long-term success.",
    "bullet9": "Sometimes medical conditions interfere with sleep. If these are left untreated, changes to your sleep routine might not be enough. Talk with your health care provider about any medical conditions you may have that may be affecting your sleep.",
    "bullet10": "Health enSuite Insomnia is based on a cognitive behavioural approach to treating insomnia. The goal is to change old ways of thinking and behaving and learn new, more effective ways of thinking and behaving. Every week, you will learn new skills to help you sleep better at night and feel better during the day. Here is an outline of what to expect in the weeks to come.",
    "topic1": "Introduction to Health enSuite Insomnia (this week)",
    "topic2": "Introduction sleep restriction therapy and using the sleep restriction clock",
    "topic3": "Changing behaviours and improving sleep hygiene",
    "topic4": "Relaxation techniques",
    "topic5": "Changing negative thoughts related to sleep",
    "topic6": "Setback prevention and planning for the future",
    "bullet11": "It may take a few weeks before you start to notice a difference in your sleep quality. Don’t get discouraged. Changing habits can be difficult and take time. The key to success is to stick with the program and practice the skills you are learning every day.",
    "bullet12": "Sleeping pills may seem like an easy way to manage your sleep. Unfortunately sleeping pills only work as a short term remedy for sleep problems. After a few weeks, sleeping pills can become less effective in promoting good sleep. But many people continue using sleeping pills for weeks or even years. This can happen even when there are adverse side effects like daytime drowsiness and difficulty concentrating.",
    "bullet13": "Your health care provider has recommended a plan that will gradually reduce the amount of the sleeping pills you are taking. The goal is for you to eventually be able to stop taking sleeping pills and get a good night’s sleep.",
    "bullet14": "How is it going so far?",
    "subHead3": "Which of the following best describes your feelings about this plan?",
    "bullet15": "Sudden changes in medications increase your risk of withdrawal symptoms.",
    "bullet16": "The risk of withdrawal symptoms is reduced when medication changes are slow and gradual. The plan your health care provider has recommended takes this slow, gradual approach. Your sleeping pill dose is reduced slowly over a period of many weeks or months. A small change happens each time you start a new dose.",
    "bullet17": "You might find that your insomnia initially gets worse after you reduce your medication. Try your best to stick to the medication plan even if this happens. Over time, your body will adjust to the new dose. It should get easier within a few days.",
    "bullet18": "Sometimes people think that they need the pills to sleep. This is a myth.",
    "bullet19": "Even if your sleep problems initially get worse when you reduce your medications, this does not mean that you will never be able to sleep well without taking medication.",
    "bullet20": "Over the next few weeks you will learn strategies for managing your sleep that will make it possible for you stop taking sleeping pills and get a good night’s sleep.",
    "bullet21": "Having someone to support you can make changing your thoughts and behaviours easier. Is there someone who can support you? This could be a romantic partner, family member, friend or someone else you feel supports you. If you regularly share a bed with another person, it is good idea to involve this person. They can play an important role in helping you change your routines around sleep.",
    "radioQ1": "Which of these best describes your situation? (Choose the option that describes your typical sleeping arrangement)",
    "radioQ2": "Would you like to nominate a support person to help you throughout this program? This person will be sent tips and information related to the skills you are learning.",
    "radioQ3": "Would you like to nominate your roommate to support you throughout this program? This person will be sent tips and information related to the skills you are learning.",
    "radioQ4": "",
    "subHead4": "Things to do this week:",
    "bullet22": "Use the sleep diary to track when you go to bed at night and when you get up in the morning. Record your sleep quality each day. Note the dose of any medications you are taking. To advance to the next level you will need to complete at least 5 of these entries.",
    "bullet23": "",
    "bullet24": "",
    "bullet25": "",
  };

  var hours = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18'];

